/** @type {import('tailwindcss').Config} */
const rgb = (v) => `rgb(var(--color-${v}-rgb) / <alpha-value>)`;
const css = (v) => `var(--color-${v})`;

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        page: rgb('page'),
        brand: {
          DEFAULT: rgb('brand'),
          hover: css('brand-hover'),
          active: css('brand-active'),
          bg: css('brand-bg'),
          border: css('brand-border'),
          50: '#F0FDFA',
          100: '#CCFBF1',
          200: '#99F6E4',
          300: '#5EEAD4',
          400: '#2DD4BF',
          500: '#14B8A6',
          600: '#0D9488',
          700: '#0F766E',
          800: '#115E59',
          900: '#134E4A',
        },
        accent: {
          DEFAULT: rgb('accent'),
          hover: css('accent-hover'),
          bg: css('accent-bg'),
        },
        ai: {
          DEFAULT: rgb('ai'),
          bg: css('ai-bg'),
          border: css('ai-border'),
        },
        'surface': rgb('surface'),
        'surface-secondary': rgb('surface-secondary'),
        'surface-tertiary': rgb('surface-tertiary'),
        'surface-elevated': rgb('surface-elevated'),
        'surface-border': rgb('surface-border'),
        'surface-border-hover': rgb('surface-border-hover'),
        'surface-border-strong': rgb('surface-border-strong'),
        'text-primary': rgb('text-primary'),
        'text-secondary': rgb('text-secondary'),
        'text-tertiary': rgb('text-tertiary'),
        'text-disabled': rgb('text-disabled'),
        'dark-surface': rgb('surface'),
        'dark-surface-secondary': rgb('surface-secondary'),
        'dark-surface-tertiary': rgb('surface-tertiary'),
        'dark-surface-elevated': rgb('surface-elevated'),
        'dark-surface-border': rgb('surface-border'),
        'dark-text-primary': rgb('text-primary'),
        'dark-text-secondary': rgb('text-secondary'),
        'dark-text-tertiary': rgb('text-tertiary'),
        success: {
          DEFAULT: rgb('success'),
          500: rgb('success'),
          600: rgb('success'),
          bg: css('success-bg'),
          border: css('success-border'),
        },
        warning: {
          DEFAULT: rgb('warning'),
          500: rgb('warning'),
          600: rgb('warning'),
          bg: css('warning-bg'),
          border: css('warning-border'),
        },
        error: {
          DEFAULT: rgb('error'),
          500: rgb('error'),
          600: rgb('error'),
          bg: css('error-bg'),
          border: css('error-border'),
        },
        info: {
          DEFAULT: rgb('info'),
          500: rgb('info'),
          600: rgb('info'),
          bg: css('info-bg'),
          border: css('info-border'),
        },
      },
      fontSize: {
        'display-lg': ['3.5rem', { lineHeight: '1.1', letterSpacing: '-0.03em' }],
        'display-md': ['2.5rem', { lineHeight: '1.15', letterSpacing: '-0.02em' }],
        'display-sm': ['2rem', { lineHeight: '1.2', letterSpacing: '-0.01em' }],
        h1: ['2rem', { lineHeight: '1.25', letterSpacing: '-0.02em' }],
        h2: ['1.5rem', { lineHeight: '1.3', letterSpacing: '-0.01em' }],
        h3: ['1.25rem', { lineHeight: '1.35', letterSpacing: '-0.005em' }],
        h4: ['1.125rem', { lineHeight: '1.4', letterSpacing: '0' }],
        'body-lg': ['1.125rem', { lineHeight: '1.6', letterSpacing: '0.01em' }],
        'body': ['1rem', { lineHeight: '1.6', letterSpacing: '0.01em' }],
        'body-sm': ['0.875rem', { lineHeight: '1.55', letterSpacing: '0.01em' }],
        caption: ['0.75rem', { lineHeight: '1.45', letterSpacing: '0.02em' }],
        label: ['0.875rem', { lineHeight: '1.5', letterSpacing: '0.01em' }],
        button: ['0.875rem', { lineHeight: '1.2', fontWeight: '600', letterSpacing: '0.02em' }],
      },
      borderRadius: {
        none: '0', sm: '0.25rem', DEFAULT: '0.5rem', md: '0.5rem',
        lg: '0.75rem', xl: '1rem', '2xl': '1.5rem', full: '9999px',
      },
      boxShadow: {
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        DEFAULT: 'var(--shadow-default)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        '2xl': '0 24px 45px 2px rgba(16, 24, 40, 0.10), 0 8px 16px -4px rgba(16, 24, 40, 0.08)',
        inner: 'inset 0 2px 4px 0 rgba(16, 24, 40, 0.05)',
      },
      transitionTimingFunction: {
        'out': 'cubic-bezier(0.22, 1, 0.36, 1)',
      },
      animation: {
        'fade-in': 'fade-in 0.4s cubic-bezier(0.22, 1, 0.36, 1) both',
        'fade-in-up': 'fade-in-up 0.5s cubic-bezier(0.22, 1, 0.36, 1) both',
        'scale-in': 'scale-in 0.25s cubic-bezier(0.22, 1, 0.36, 1) both',
        'shimmer': 'shimmer 1.6s linear infinite',
        'pop': 'pop 0.35s cubic-bezier(0.34, 1.56, 0.64, 1) both',
        'float': 'float 6s ease-in-out infinite',
      },
      keyframes: {
        'fade-in': { from: { opacity: '0' }, to: { opacity: '1' } },
        'fade-in-up': { from: { opacity: '0', transform: 'translateY(14px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'scale-in': { from: { opacity: '0', transform: 'scale(0.96)' }, to: { opacity: '1', transform: 'scale(1)' } },
        'shimmer': { from: { backgroundPosition: '-200% 0' }, to: { backgroundPosition: '200% 0' } },
        'pop': { '0%': { opacity: '0', transform: 'scale(0.6)' }, '100%': { opacity: '1', transform: 'scale(1)' } },
        'float': { '0%, 100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-8px)' } },
      },
      container: {
        center: true,
        padding: {
          DEFAULT: '1.5rem', sm: '1.5rem', md: '2rem',
          lg: '2.5rem', xl: '3rem', '2xl': '4rem',
        },
      },
      aspectRatio: { '16-9': '16 / 9', '4-3': '4 / 3', '1-1': '1 / 1' },
    },
  },
}

